openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
paths:
  /api/notes/{path}:
    put:
      summary: Save or update a note
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: Note saved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: Unauthorized
        '500':
          description: Server error